apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aliasvault.fullname" . }}
  labels:
    {{- include "aliasvault.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "aliasvault.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aliasvault.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "aliasvault.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            {{- if .Values.service.smtp.enabled }}
            - name: smtp
              containerPort: 25
              protocol: TCP
            - name: submission
              containerPort: 587
              protocol: TCP
            {{- end }}
          env:
            - name: HOSTNAME
              value: {{ .Values.config.hostname | quote }}
            - name: PUBLIC_REGISTRATION_ENABLED
              value: {{ .Values.config.publicRegistrationEnabled | quote }}
            - name: IP_LOGGING_ENABLED
              value: {{ .Values.config.ipLoggingEnabled | quote }}
            - name: FORCE_HTTPS_REDIRECT
              value: {{ .Values.config.forceHttpsRedirect | quote }}
            - name: SUPPORT_EMAIL
              value: {{ .Values.config.supportEmail | quote }}
            - name: PRIVATE_EMAIL_DOMAINS
              value: {{ .Values.config.privateEmailDomains | quote }}
            - name: SMTP_TLS_ENABLED
              value: {{ .Values.config.smtpTlsEnabled | quote }}
            - name: SMTP_ADVERTISED_HOSTNAME
              value: {{ .Values.config.smtpAdvertisedHostname | quote }}
            - name: DATA_PROTECTION_CERT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "aliasvault.secretName" . }}
                  key: {{ .Values.secret.dataProtectionCertPasswordKey }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: database
              mountPath: /database
            - name: logs
              mountPath: /logs
            - name: secrets
              mountPath: /secrets
            - name: certificates
              mountPath: /certificates
            {{- end }}
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: database
          persistentVolumeClaim:
            claimName: {{ include "aliasvault.fullname" . }}-database
        - name: logs
          persistentVolumeClaim:
            claimName: {{ include "aliasvault.fullname" . }}-logs
        - name: secrets
          persistentVolumeClaim:
            claimName: {{ include "aliasvault.fullname" . }}-secrets
        - name: certificates
          persistentVolumeClaim:
            claimName: {{ include "aliasvault.fullname" . }}-certificates
        {{- end }}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
