{{- if .Values.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aliasvault.fullname" . }}-database
  labels:
    {{- include "aliasvault.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.database.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aliasvault.fullname" . }}-logs
  labels:
    {{- include "aliasvault.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.logs.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aliasvault.fullname" . }}-secrets
  labels:
    {{- include "aliasvault.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.secrets.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aliasvault.fullname" . }}-certificates
  labels:
    {{- include "aliasvault.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.certificates.size }}
{{- end }}
