apiVersion: v1
kind: Service
metadata:
  name: {{ include "aliasvault.fullname" . }}
  labels:
    {{- include "aliasvault.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.service.smtp.enabled }}
    - port: {{ .Values.service.smtp.port }}
      targetPort: smtp
      protocol: TCP
      name: smtp
    - port: {{ .Values.service.smtp.submissionPort }}
      targetPort: submission
      protocol: TCP
      name: submission
    {{- end }}
  selector:
    {{- include "aliasvault.selectorLabels" . | nindent 4 }}
