apiVersion: v1
entries:
  aliasvault:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2026-04-17T17:32:09.410261206Z"
    description: A Helm chart for Kubernetes
    digest: 91d30809c4abd015513b532de62389dff812cc451f34c82895392c6653de9f9b
    name: aliasvault
    type: application
    urls:
    - https://github.com/d-o-it/helm-charts/releases/download/sankeymatic-0.1.0/aliasvault-0.1.0.tgz
    version: 0.1.0
  sankeymatic:
  - apiVersion: v2
    appVersion: latest
    created: "2026-04-17T17:32:09.410754376Z"
    description: A Helm chart for Kubernetes deployment of SankeyMATIC
    digest: 6efc0a4cb536bea7fc7243887907a1d818dc5af5df680f036b1c514d5b6f0ddd
    name: sankeymatic
    type: application
    urls:
    - https://github.com/d-o-it/helm-charts/releases/download/sankeymatic-0.1.0/sankeymatic-0.1.0.tgz
    version: 0.1.0
generated: "2026-04-17T17:32:09.409512639Z"
